SalesForceRoundSix/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participantes do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesForceRoundSix/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Utilizado para informar se o jogador foi eliminado</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

SalesForceRoundSix/force-app/main/default/objects/Jogador__c/fields/Forca__c.field-meta.xml
<CustomField>
    <fullName>Forca__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Força do jogador</description>
    <inlineHelpText>Força do jogador</inlineHelpText>
    <label>Força</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesForceRoundSix/force-app/main/default/objects/Jogador__c/fields/Inteligencia__c.field-meta.xml
<CustomField>
    <fullName>Inteligencia__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Inteligência do jogador</description>
    <inlineHelpText>Inteligência do jogador</inlineHelpText>
    <label>Inteligência</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesForceRoundSix/force-app/main/default/objects/Jogador__c/fields/Velocidade__c.field-meta.xml
<CustomField>
    <fullName>Velocidade__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Velocidade do jogador</description>
    <inlineHelpText>Velocidade do jogador</inlineHelpText>
    <label>Velocidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesForceRoundSix/force-app/main/default/classes/TesteClasse.cls
public with sharing class TesteClasse {
    public TesteClasse() {       
    }

    public void execute()
    {
        Jogador__c atacante;
        Jogador__c defensor;

        List<Jogador__c> listJogadoresVivos = BuscaJogadoresVivos(); 

        ObterAtacanteDefensor(listJogadoresVivos, atacante, defensor);

        Jogador__c JogaodorVencedor = Confronto(atacante, defensor);
        
        if (JogaodorVencedor != null)
        {
            Jogador__c jogador = new Jogador__c();
            jogador.Id = participantes[i].Jogador__c;
            jogador.Eliminado__c = true;
            jogadores.add(jogador);
            
            insert  JogaodorVencedor;
        }
    }

//Busca por clientes vivos
    public List<Jogador__c> BuscaJogadoresVivos() {
         List<Jogador__c> JogadoresVivos = [SELECT Id, Eliminado__c, Inteligencia__c, Velocidade__c 
         FROM Jogador__c WHERE Eliminado__c = false];
         
         return JogadoresVivos;
    }

//Busca o atacante e Defensor do jogo
public void ObterAtacanteDefensor(List<Jogador__c> Jogadores, Jogador__c Atacante, Jogador__c Defensor) 
{
    Integer listSize = Jogadores.size() - 1;
    
    Integer PosicaoRandom = Integer.valueof((Math.random() * listSize));

    Atacante = Jogadores[PosicaoRandom];
    Defensor = Jogadores[PosicaoRandom + 1];   
  
}

public Jogador__c Confronto (Jogador__c atacante, Jogador__c defensor) {
    
    bool ExisteVencedor = false;
    Jogador__c Vencedor = null;

    Integer qtdD20 = 0;
    Integer qtdD10 = 0;

   if ((qtdD20 + atacante.Forca__c) > (qtdD10 + defensor.Velocidade__c + defensor.Inteligencia__c))
   {
       ExisteVencedor = true;
       defensor.Eliminado__c = true;
       Vencedor = atacante;
   }
   else  if (qtdD20 == 1)
   {
        qtdD20 = 0;
        qtdD10 = 0;

        if ((qtdD20 + defensor.Forca__c) > (qtdD10 + atacante.Velocidade__c + atacante.Inteligencia__c))
        {
            ExisteVencedor = true;
            defensor.Eliminado__c = true;
            Vencedor = defensor;
        }
   }

   if (ExisteVencedor)
      return Vencedor;
   else
      return null;
    
}


}