SalesForceRoundSix/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participantes do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesForceRoundSix/force-app/main/default/objects/Jogador__c/fields/DataMorte__c.field-meta.xml
<CustomField>
    <fullName>DataMorte__c</fullName>
    <description>Usado para a data da morte</description>
    <inlineHelpText>Data da morte do jogador</inlineHelpText>
    <label>Data da Morte</label>
    <type>DateTime</type>
</CustomField>

SalesForceRoundSix/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Utilizado para informar se o jogador foi eliminado</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

SalesForceRoundSix/force-app/main/default/classes/JogadoresTriggerHandler.cls
public with sharing class JogadoresTriggerHandler {
   
    public static void beforeUpdate(List<Jogador__c> records, Map<Id, Jogador__c> oldMap) {
        for (Jogador__c jogador : records)
        {
            beforeUpdate(jogador, oldMap.get(jogador.Id));
        }
    }

    private static void beforeUpdate(Jogador__c record, Jogador__c recordOld)
    {
        if (isChanged(record, recordOld, Jogador__c.Eliminado__c))
        {
            setValue(record, Jogador__c.DataMorte__c, System.now());
        }
    }

    private static boolean isChanged(Jogador__c record, Jogador__c recordTocompare, Schema.SObjectField fieldToValued)
    {
        return  isChanged(record.get(fieldToValued), recordTocompare.get(fieldToValued));
    }

    private static boolean isChanged(Object value, Object valueTocompare)
    {
        return value != valueTocompare;
    }

    private static void setValue (Jogador__c record, SObjectField field, Object value)
    {
        record.put(field, value);
    }
}